### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [richard4339/powerbuilder.tmbundle#1]
I would like to use your grammar for PowerBuilder but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by richard4339** [comment]
Done.

However, I'd like to point out that this might not be the best place to start anymore. I quickly created this 5 years ago for Sublime, and literally used the [default VB bundle](https://github.com/textmate/asp.vb.net.tmbundle) and changed the extensions for the first step. There have been 5 additional changes since then on the parent, plus some other outside changes made by TextMate. I never took this much further simply because I stopped using Sublime.

Either way, feel free to take this and modify as you wish.

**Comment by pchaigno** [comment]
Thanks!

We're also looking into using [rolando3/language-powerbuilder](https://github.com/rolando3/language-powerbuilder). We'll test both with [Lightshow](https://github-lightshow.herokuapp.com/) to make sure they work as expected ;)

**Comment by richard4339** [comment]
I've got a Notepad++ language file somewhere too, that's a tweaked version of one originally linked off the NPP site:. If I can find it I'll throw it on Github too.

**Comment by pchaigno** [comment]
GitHub can only use TextMate/Atom/Sublime Text grammars :/
It might be useful to someone else though.

**Comment by richard4339** [comment]
That's more the point.

On Monday, June 27, 2016, Paul Chaignon notifications@github.com wrote:

> GitHub can only use TextMate/Atom/Sublime Text grammars :/
> It might be useful to someone else though.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/richard4339/powerbuilder.tmbundle/issues/1#issuecomment-228725155,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAGJxHgTzm_x83cqo4T7WSjxyXWJsFhMks5qP7ocgaJpZM4I-oCa
> .

## 

Richard
richard@mozor.net
